[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildTimeout = 1800  # 30 minutes build timeout

[deploy]
startCommand = "catalina.sh run"
healthcheckPath = "/api/v1/user-settings/1"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
interval = "30s"
timeout = "10s"
retries = 3
startPeriod = "60s" 